version: '3'
services:
  postgres:
    image: "postgres:latest"
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  data-generator:
    build: ./data-generator/server/
    ports:
      - "8088:8080"
  zookeeper:
    image: "debezium/zookeeper:0.9.5.Final"
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: "debezium/kafka:0.9.5.Final"
    ports:
      - "9092:9092"
    links:
      - "zookeeper"
    environment:
      - "ZOOKEEPER_CONNECT=zookeeper:2181"
  connect:
    image: "debezium/connect:0.9.5.Final"
    ports:
      - "8083:8083"
    links:
      - "kafka"
      - "postgres"
    environment:
      - "BOOTSTRAP_SERVERS=kafka:9092"
      - "GROUP_ID=1"
      - "CONFIG_STORAGE_TOPIC=my_connect_configs"
      - "OFFSET_STORAGE_TOPIC=my_connect_offsets"
      - "STATUS_STORAGE_TOPIC=my_connect_statuses"

volumes:
  postgres: